### ISSUE TITLE
__floordiv__ in utils.py

### ISSUE THREAD

**Issue by DamienAllonsius** [aig-upf/gridenvs#6]
@mjunyentb  are you sure about your function __floordiv__ ? It seems that you copy pasted the function __truediv__ without replacing "/" by "//". Is that made on purpose ?

**Comment by mjunyentb** [comment]
Yeah that's probably an issue. Actually, that was meant to be small helper class but it's getting big. I suggest we remove it and use something else, like a numpy array.

**Comment by DamienAllonsius** [comment]
Personally I find this class **Point** very useful...
